#!/bin/sh

clear
cd /

# Make it so we can eject the live cd.
echo "Please wait..."
sleep 15
/etc/init.d/modloop stop
sleep 5
umount /media/cdrom
sleep 5

/etc/init.d/networking start && /bin/mpc_network.rs

sleep 10000000
