#!/bin/sh

clear
cd /

# Make it so we can eject the live cd.
/etc/init.d/modloop stop
sleep 5
umount /media/cdrom
sleep 5

rm /dev/grsec
mknod -m 622 /dev/grsec c 1 13
gradm -E

su - compute -c /bin/mpc_compute.rs

sleep 10000000
